package jp.co.equinestudio.racing.dao.green;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jp.co.equinestudio.racing.dao.green.FavoriteHorse;

import jp.co.equinestudio.racing.dao.green.FavoriteHorseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteHorseDaoConfig;

    private final FavoriteHorseDao favoriteHorseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteHorseDaoConfig = daoConfigMap.get(FavoriteHorseDao.class).clone();
        favoriteHorseDaoConfig.initIdentityScope(type);

        favoriteHorseDao = new FavoriteHorseDao(favoriteHorseDaoConfig, this);

        registerDao(FavoriteHorse.class, favoriteHorseDao);
    }
    
    public void clear() {
        favoriteHorseDaoConfig.getIdentityScope().clear();
    }

    public FavoriteHorseDao getFavoriteHorseDao() {
        return favoriteHorseDao;
    }

}
